name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
# 声明需要上传权限
permissions:
  contents: write
  actions: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/setup-node@v4
        with:
          node-version: 18

          
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: ls && pwd
        
      - run: npm install -g yarn
      
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: Install dependencies
        run: yarn install
        
      - run: yarn build
            
      - name: Rename Build
        run: |
          ls
          echo "==========================="
          mv ./build ./jimmer-doc
          echo "==========================="
          ls
          
      - name: Zip
        run: |
          zip -r jimmer-doc.zip ./jimmer-doc/*
          ls
          
      - name: Upload Build Artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: jimmer-doc.zip
          path: ./jimmer-doc
          if-no-files-found: warn
          retention-days: 90
      
      - name: Upload to Release
        if: success()
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./jimmer-doc.zip
          asset_name: jimmer-doc.zip
          tag: release
