name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
# 声明需要上传权限
permissions:
  contents: write
  actions: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn build
      
      - name: 压缩文件
        run: |
          tar -zcvf build.tar.gz ./build

      # Step 12: 上传到当前构建的 Artifact
      - name: Upload APK Artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build.tar.gz
          path: build.tar.gz
          if-no-files-found: warn
          retention-days: 90
